# Generated by Django 4.0.6 on 2022-08-02 22:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inicio', '0002_alter_blog_contenido'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='contenido',
            field=models.TextField(null=True),
        ),
    ]
