# Generated by Django 4.0.6 on 2022-08-02 23:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inicio', '0004_alter_blog_contenido'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='autor',
            field=models.CharField(default=0, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='blog',
            name='fecha_creacion',
            field=models.DateField(null=True),
        ),
    ]
